### ISSUE TITLE
Variable products pricing display

### ISSUE THREAD

**Issue by jardinec** [strangerstudios/pmpro-woocommerce#129]
Hi,

Small bug I think if all product variations are the same price.

Output shows as £10.00 - £10.00 rather then just a single £10.00

inside --> pmprowoo_woocommerce_variable_price_html

I just edited the final return clause to say:
`    if($member_min_price === $member_max_price){
    	return wc_price($member_min_price);
    }
    else{
	    return wc_format_price_range( $member_min_price, $member_max_price);
	}`

There may be better ways of achieving the same goal.

Craig

**Comment by michaelbeil** [comment]
**Describe the bug**
A s reported in this [ticket (**moderators only**)](https://www.paidmembershipspro.com/forums/topic/woocommerce-add-on-3/):

>I am using the woocommerce add on and I noticed that even with the same product price for variations, it will give a range. I have multiple products that have different sizes but are the same price. 

>Without the plugin activated it loads correctly with a single price.


**To Reproduce**
Steps to reproduce the behavior:
1. Add a variation product, the variation product shows $19.00-19.00 
2. Deactivate Paid Memberships Pro - WooCommerce Add On, the variation product shows $19.00.

**Expected behavior**
I expected the price to not be duplicated.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.5.9.1, Paid Memberships Pro - WooCommerce Add On 1.7.2, WooCommerce 5.4.1, Twenty Twenty-One 1.2, WP 5.7.2, and PHP 7.4.1,  
```
</details>

**Comment by andrewlimaza** [comment]
Thanks Craig, this has been pushed to our dev branch. I tweaked it slightly but almost identical, gave you props. Thanks for contributing to Paid Memberships Pro!
