### ISSUE TITLE
User Membership doubles

### ISSUE THREAD

**Issue by LPtheblogger** [strangerstudios/pmpro-woocommerce#163]
Hi, I don’t know why if membership doubles times 2? For example, if set to 30 days, it doubled to 60days with woocommerce addon.
Any help?

**Comment by mircobabini** [comment]
It should be fixed in the latest (released 3 days ago). Are you up to date?

Check the related PR: https://github.com/strangerstudios/pmpro-woocommerce/pull/160

**Comment by andrewlimaza** [comment]
@LPtheblogger please can you open a support ticket on www.paidmembershipspro.com/support or the repo - https://wordpress.org/plugins/pmpro-woocommerce/ as I haven't been able to replicate this issue.

This issue seems to be site specific, the expiration date is correctly applying to my test account on my development environment. 

In Github, we do not offer support as we don't actively monitor these issues as we do our support system or .org. I am going to close this issue. Thank you for understanding.
