### ISSUE TITLE
Membership Price Didn't Apply

### ISSUE THREAD

**Issue by aukrit** [strangerstudios/pmpro-woocommerce#19]
![screen shot 2014-09-02 at 1 26 23 pm](https://cloud.githubusercontent.com/assets/1538964/4113587/011ee776-3251-11e4-8674-a58bf8412f8c.png)

Hi I tried to setup PMPro with WooCommerce.

After install PM WooCommerce plugin, I setup membership products:
- Silver Membership ($20.00/month) <- set as "Silver" member under Membership tap
- Gold Membership ($30.00/month) <- set as "Gold" member under Membership tab

Ideally, I would like to allow end user to upgrade their membership level.
Let say if you are "silver" member, if you purchase "Gold Membership" product, the upgrade price I need is $15.00 extra.

I went to "Gold Membership" product and set price under "Membership" tab to 30.00 for free user, 15.00 for silver and 0 for gold member.
I also set "Silver Membership" product to 20 for free, 0 for silver and 0 for gold.

However, when I tried to access to the site, with anonymous user, I bought the "Silver Membership" at $20, then when I went to the ship again, I still see "Gold Membership" still full-price ($30). Tried to add to cart and go to checkout process but it still full price. What I did wrong?

Also, another question is how to hide some product for different membership level? For example, If I'm silver member, I don't want to see "Silver Membership" in the shop. Is there anywhere I can set this up on the product page?

Thank you

NOTE: 
Paid Memberships Pro 1.7.13.1
PMPro WooCommerce 1.2.5.1
WooCommerce 2.1.12
WordPress 3.9.2

**Comment by raj638** [comment]
I am also facing same problem
Please advise need guidance.

Thanks

**Comment by MarkhamHaynes** [comment]
I see the same behavior. The pricing works as expected only if the product is NOT identified as a "membership product".

**Comment by jaredtm13** [comment]
I also found that the pricing only works if you make the product not a membership product. This basically makes the plugin useless. Unfortunate. Anyone, have any luck making it work? Any tips? PMPRO, please advise.

**Comment by crashnash86** [comment]
I am also having the same issue, is there a fix for this????

**Comment by guldoe** [comment]
Hi, are any fix for this issue.  Thanks

**Comment by mummetech** [comment]
Just because I have seen this too many times... this plugin does two things
1- Allows your user to buy a membership through a Woo Commerce product
2- Allows you to sell a Woo Commerce product at a discount to your members

#1 uses the Membership Level setting (to give the user that membership level when they buy the product)
#2 uses the boxes below that, to assign a discounted price for the product to your memberships

You can not use BOTH sections, you can not give a member a discount on a membership with this plugin, if you need to do that use a coupon.... So to recap - to give a member a discount on a product, be sure to set "Membership Product" to "None".  If you want to sell a membership with woo, set the membership product to the level you want the user to get by purchasing that product and leave the boxes below alone.

**Comment by andrewlimaza** [comment]
Thanks for clearing this up @mummetech, there is now an option under "Advanced Settings" that allows you to discount membership assigned products as well.
