### ISSUE TITLE
Show Membership Discounts on Checkout Screen

### ISSUE THREAD

**Issue by dap10** [strangerstudios/pmpro-woocommerce#40]
Hi,

Just wondering how I show membership discounts on the checkout screen and also on the product list of prices displayed in the shop so members know the discount they are receiving

Many Thanks

David

**Comment by andrewlimaza** [comment]
Here is a gist for anyone that may stumble upon this issue - https://gist.github.com/andrewlimaza/4ddd2ca1c57951800a8583db347974fd

Due to the inactivity and age of this issue I am going to close it and mark it as "resolved" if you are still having this issue please open a support ticket on https://www.paidmembershipspro.com or log any bug/issues in this repository.

Thank you for understanding.
