### ISSUE TITLE
Q: Can this be used to layer multiple memberships?

### ISSUE THREAD

**Issue by woodwardmatt** [strangerstudios/pmpro-woocommerce#45]
I was wondering if a user with an existing & active PMPRO membership, could use this integration to purchase additional memberships add-ons (think extra features that you'd charge a subscription for, as opposed to swapping / upgrading membership types)? If so, how is the pricing meant to be configured for the membership / product to ensure the subscription for the payment is activated rather than initiating a one-time purchase?

Happy to hear other suggestions if this is not how this integration was intended to be used.

Cheers!

**Comment by strangerstudios** [comment]
Short answer: not right now.

We have an addon to add support for multiple memberships per user using just PMPro (no WooCommerce) here: https://github.com/strangerstudios/pmpro-multiple-memberships-per-user

That addon works with just PMPro, but a lot of our other addons aren't coded to understand what to do when a user has multiple membership levels at once. For example, the email marketing addons are coded to remove users from "old" level lists when they switch levels... it doesn't understand that you might be adding a level without removing the old one. All of our addons have to be updated to support this. It's going to take time.

So you can play with that a bit and see if it works for you and/or if you don't mind helping to update the addons that need it.

RE having multiple memberships at a time with WooCommerce, WC Subs, and PMPro... that wouldn't be possible yet, but in this most recent round of fixes/updates I did I realized how we would be able to do that. I've taken some notes and hope to add that functionality at some time. In short, our functions in PMPro WC that remove levels should be updated to use the pmpro_cancelMembershipLevel instead of pmpro_changeMembershipLevel. That might be it, or it might need some more work/thought. I didn't want to introduce another fault point in this latest release so held off on that.

**Comment by michaelbeil** [comment]
This  came up in a [ticket **moderators only**](https://contact.paidmembershipspro.com/conversation/29712?folder_id=17):

> I am unable to enroll for more than one course. It say's "You may only add one membership to your cart". I know i have tick some checkbox for the same but now i don't remember the exact setting. Please help.

We have an Add On to add support for multiple memberships per user using just PMPro (not WooCommerce) called Multiple Memberships Per User Plus Add On. That Add On works with just PMPro, but a lot of our other Add Ons, including WooCommerce, aren't coded to understand what to do when a user has multiple membership levels at once. For example, the email marketing Add Ons are coded to remove users from "old" level lists when they switch levels, PMPro doesn't understand that you might be adding a level without removing the old one. All of our Add Ons have to be updated to support this and it's going to take time.

**Comment by andrewlimaza** [comment]
Multiple Memberships Per User does integrate with WooCommerce and allows customer's to purchase multiple membership products within a single cart.

Due to the age of this issue, I am going to close this ticket. Any new issues relating to MMPU and Paid Memberships Pro WooCommerce Integration may be handled by creating a support ticket on www.paidmembershipspro.com or creating an issue on this repository (if it's a bug).

Thank you for understanding.
