### ISSUE TITLE
Problem with function within function?

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/pmpro-woocommerce#75]
Client solved problem myself with:

`$level_price = get_post_meta($product->get_id(), $level_price, true);`

that I transformed into:

`$level_price = get_post_meta($product->ID, $level_price, true);
`
https://www.paidmembershipspro.com/forums/topic/woocommerce-price-for-members/#post-138135

**Comment by pbrocks** [comment]
`
	/**
	 * Get the ID.
	 *
	 * @return int
	 */
	public function get_id() {
		return $this->data['id'];
	}`

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-attribute.php#L199-L206

**Comment by eighty20results** [comment]
Hmm..

get_post_meta() shouldn't have problems with calling a function to return a $post_ID, so this is odd.

However, rather than using a (now defunct) magic method for the product ID, I think we should do a call for $product->get_id() and assign it to a `$product_id` variable since using the magic method triggers "deprecated" warnings and is why the function call was used in the first place. 

Being addressed in #86

**Comment by ideadude** [comment]
Merged Thomas' PR and changed this in a few other spots. I think it might just be funny WC versions, but did the change anyway.
